services:
  cronjobs:
    build:
      context: $ODOO_IMAGES/cronjobs
      args:
        WODOO_VERSION: $WODOO_VERSION
        POSTGRES_VERSION: $POSTGRES_VERSION
        APT_PROXY_IP: ${APT_PROXY_IP}
        PYPI_SERVER: ${PYPI_SERVER}
        # Dont do: if images used, then not compatible
        # OWNER_UID: $OWNER_UID
    privileged: true
    restart: "unless-stopped"
    command: ["daemon"]
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
    volumes:
      - "$ODOO_IMAGES/cronjobs/bin/:/usr/local/bin/:ro"
      - "${HOST_RUN_DIR}/cronjobs:/opt/cronjobs"
      - "$DUMPS_PATH:/host/dumps"
      - "${HOST_RUN_DIR}:/root/.odoo/run/$PROJECT_NAME"
      - "${ODOO_IMAGES}:$ODOO_IMAGES"
      - ${HOST_CUSTOMS_DIR}:/opt/src
      - ${HOST_CUSTOMS_DIR}:${HOST_CUSTOMS_DIR}
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker
      - "${ODOO_IMAGES}/cronjobs/bin/postgres.py:/usr/local/bin/postgres.py"
      - "${ODOO_IMAGES}/cronjobs/bin/run.py:/usr/local/bin/run.py"
