repos:
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0  # Use latest stable tag: https://github.com/hadolint/hadolint/releases
    hooks:
      - id: hadolint
        name: Lint Dockerfiles
        files: (^|/)Dockerfile([^/]*$)