#manage-order: 6000
services:
  router:
    container_name: odoo_router
    build: ${HOST_RUN_DIR}/router
    restart: unless-stopped
    networks:
      - default
    ports:
      - "${BINDING_80:-80}:80"
      - "${BINDING_443:-443}:443"
    volumes:
      - ${HOST_RUN_DIR}/router/nginx.conf:/etc/nginx/nginx.conf
      - ${HOST_RUN_DIR}/router/sites-enabled:/etc/nginx/sites-enabled
      - ${HOST_RUN_DIR}/router/sites-available:/etc/nginx/sites-available
      - ${HOST_RUN_DIR}/router/www:/var/www:ro
      - ${HOST_RUN_DIR}/router/letsencrypt:/etc/letsencrypt
      - ${HOST_RUN_DIR}/router/htpasswd:/htpasswd
      - ${HOST_RUN_DIR}/router/custom_ssl:/etc/ssl/custom_ssl
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
