# proxy_host: odoo:8069
location / {
    set $backend $default_target;
    access_by_lua_file "{lua_resolve_host}";

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    proxy_pass $backend;

    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    # done in lua with fallback option (called from outside)
    #proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Port $external_port;
    proxy_set_header X-Real-IP $remote_addr;

    proxy_connect_timeout   600;
    proxy_send_timeout      600;
    proxy_read_timeout      600;

    proxy_set_header X-NginX-Proxy true;
    proxy_cache_bypass $http_upgrade;


    error_page 502 503 504 = @fallback;
}

location = /debugpython {
    # Set the cookie (1 day lifetime)
    add_header Set-Cookie "debugpython=1; Path=/; Max-Age=86400";

    # Default fallback
    set $redir "/";

    # If Referer header exists, use it
    if ($http_referer != "") {
        set $redir $http_referer;
    }

    # If Referer doesn't include http/https, rebuild absolute URL
    if ($redir !~* ^https?://) {
        set $redir "$scheme://$http_host$redir";
    }

    return 302 $redir;
}

location = /debugpython_off {
    add_header Set-Cookie "debugpython=; Path=/; Max-Age=0";
    set $redir "/";
    if ($http_referer != "") {
        set $redir $http_referer;
    }
    if ($redir !~* ^https?://) {
        set $redir "$scheme://$http_host$redir";
    }
    return 302 $redir;
}
