# manage-order 1000
volumes:
    robo_upload_files:

services:
    seleniumdriver:
        image: selenium/standalone-chromium:132.0-chromedriver-132.0-grid-4.28.1-20250202
        shm_size: 4gb
        # vnc possible at: http://localhost:7900/?autoconnect=1&password=secret⁠.
        # ports:
        #   - 7900:7900
        expose:
            - 4444
        volumes:
            - robo_upload_files:/tmp/robo_upload_files

    robot:
        build:
            context: $ODOO_IMAGES/robot
            args:
                WODOO_VERSION: $WODOO_VERSION
                OWNER_UID: ${OWNER_UID}
                DOCKER_GID: ${DOCKER_GID}
        links:
            - seleniumdriver
        cap_add:
          # required by vscode
          - SYS_ADMIN
        shm_size: 4gb
        privileged: true
        environment:
            OUTPUT_DIR: /opt/output
            OWNER_UID: ${OWNER_UID}
            ODOO_HOME: /opt/src
            ODOO_CMD: /opt/robot/.local/pipx/venvs/wodoo/bin/odoo
            BROWSER_WIDTH: 1920
            BROWSER_HEIGHT: 1080
            ROBO_NO_UI_HIGHLIGHTING: 0
            ROBO_ODOO_HOST: http://proxy:80
            ROBO_UPLOAD_FILES_DIR_LOCAL: /tmp/robo_upload_files
            ROBO_UPLOAD_FILES_DIR_BROWSER_DRIVER: /tmp/robo_upload_files
            ROBO_WEBDRIVER_BROWSER: chrome
            #ROBO_WEBDRIVER_HOST: 127.0.0.1:4444
            ROBO_WEBDRIVER_HOST: seleniumdriver:4444
            ROBO_FORCE_HEADLESS: 0
            ROBO_PARAMS_FILE: /opt/robot/robo_params.json
        profiles:
            - auto
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ${HOST_RUN_DIR}/odoo_outdir/robot_output:/opt/output
            - ${ODOO_IMAGES}/robot/robotest.py:/opt/robot/robotest.py
            - ${ODOO_IMAGES}/robot/keywords:/opt/robot/keywords
            - ${ODOO_IMAGES}/robot/library:/opt/robot/library
            - ${CUSTOMS_DIR}:/opt/src
            - ${CUSTOMS_DIR}:${CUSTOMS_DIR}
            - "${HOST_RUN_DIR}:/opt/robot/.odoo/run/$PROJECT_NAME"
            - "${ODOO_IMAGES}:/opt/robot/.odoo/images"
            - "${ODOO_IMAGES}:$ODOO_IMAGES"
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker:/var/lib/docker
            - robo_upload_files:/tmp/robo_upload_files

    novnc_cobot:
        build:
          context: $ODOO_IMAGES/novnc
          args:
            relpathname: wscobot
        restart: "unless-stopped"
        profiles:
          - manual
        links:
            - cobot
        volumes:
          - ${ODOO_IMAGES}/novnc/websockify:/root/websockify
          - ${ODOO_IMAGES}/robot/tokens:/root/tokens
        environment:
          - DISPLAY_WIDTH=${VSCODE_WIDTH}
          - DISPLAY_HEIGHT=${VSCODE_HEIGHT}
          - DISPLAY_COLOR=${VSCODE_COLOR}
          - AUTOCONNECT=true
          # - RUN_XTERM={yes|no} (yes)
          - RUN_FLUXBOX=yes
          - VNC_SERVER=cobot:5900
          - VIEW_ONLY=false
          - TOKEN_FILE=/root/tokens


    # vscode and robot framework to quickly debug/create robot tests
    cobot:
        build:
            context: $ODOO_IMAGES/robot
            args:
                WODOO_VERSION: $WODOO_VERSION
                OWNER_UID: ${OWNER_UID}
                DOCKER_GID: $DOCKER_GID
        cap_add:
          # required by vscode
          - SYS_ADMIN
        shm_size: 4gb
        entrypoint: ["/opt/robot/entrypoint_cobot.sh"]
        privileged: true
        environment:
            DISPLAY: :0
            OUTPUT_DIR: /opt/output
            OWNER_UID: ${OWNER_UID}
            ODOO_HOME: /opt/src
            ODOO_CMD: /opt/robot/.local/pipx/venvs/wodoo/bin/odoo
            DISPLAY_WIDTH: ${VSCODE_WIDTH}
            DISPLAY_HEIGHT: ${VSCODE_HEIGHT}
            DISPLAY_COLOR: ${VSCODE_COLOR}
            DEBUG_SOCKET: /tmp/debug_socket/socket
            BROWSER_WIDTH: 1024
            BROWSER_HEIGHT: 768
            ROBO_ODOO_HOST: http://odoo
            ROBO_PORT: 80
        profiles:
            - manual
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ${HOST_RUN_DIR}/robot/cobot/debug:/tmp/debug_socket/
            - ${HOST_RUN_DIR}/odoo_outdir/robot_output:/opt/output
            - ${ODOO_IMAGES}/robot/robotest.py:/opt/robot/robotest.py
            - ${ODOO_IMAGES}/robot/keywords:/opt/robot/keywords
            - ${ODOO_IMAGES}/robot/library:/opt/robot/library
            - ${CUSTOMS_DIR}:/opt/src
            - ${CUSTOMS_DIR}:${CUSTOMS_DIR}
            - "${HOST_RUN_DIR}:/opt/robot/.odoo/run/$PROJECT_NAME"
            - "${ODOO_IMAGES}:/opt/robot/.odoo/images"
            - "${ODOO_IMAGES}:$ODOO_IMAGES"
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker:/var/lib/docker
            # TODO
            # - /home/parallels/projects/wodoo:/home/parallels/projects/wodoo

    robot_file_browser:
        build: $ODOO_IMAGES/static_file_browser
        restart: unless-stopped
        profiles:
            - auto
        networks:
            - default
        environment:
            - FILE_FOLDER=/robot_output
            - URL_PATH=/robot-output
        volumes:
            - $HOST_RUN_DIR/run/intercom:/intercom
            - $ODOO_IMAGES/static_file_browser/app/server.js:/usr/src/app/server.js
            - ${CUSTOMS_DIR}:/usr/src/app/odoo
            - ${HOST_RUN_DIR}/odoo_outdir/robot_output:/robot_output

        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"