# manage-order 1000
services:
    robot:
        build:
            context: $ODOO_IMAGES/robot
            args:
                WODOO_VERSION: $WODOO_VERSION
                OWNER_UID: ${OWNER_UID}
        privileged: true
        environment:
            OUTPUT_DIR: /opt/output
            OWNER_UID: ${OWNER_UID}
            ODOO_HOME: /opt/src
            ODOO_CMD: /opt/robot/.local/pipx/venvs/wodoo/bin/odoo
        profiles:
            - auto
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ${HOST_RUN_DIR}/odoo_outdir/robot_output:/opt/output
            - ${ODOO_IMAGES}/robot/robotest.py:/opt/robot/robotest.py
            - ${ODOO_IMAGES}/robot/keywords:/opt/robot/keywords
            - ${ODOO_IMAGES}/robot/library:/opt/robot/library
            - ${CUSTOMS_DIR}:/opt/src
            - ${CUSTOMS_DIR}:${CUSTOMS_DIR}
            - "${HOST_RUN_DIR}:/opt/robot/.odoo/run/$PROJECT_NAME"
            - "${ODOO_IMAGES}:/opt/robot/.odoo/images"
            - "${ODOO_IMAGES}:$ODOO_IMAGES"
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker:/var/lib/docker

    robot_file_browser:
        build: $ODOO_IMAGES/static_file_browser
        restart: unless-stopped
        profiles:
            - auto
        networks:
            - default
        environment:
            - FILE_FOLDER=/robot_output
            - URL_PATH=/robot-output
        volumes:
            - $HOST_RUN_DIR/run/intercom:/intercom
            - $ODOO_IMAGES/static_file_browser/app/server.js:/usr/src/app/server.js
            - ${CUSTOMS_DIR}:/usr/src/app/odoo
            - ${HOST_RUN_DIR}/odoo_outdir/robot_output:/robot_output

        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"