#manage-order: 12000
version: "3.3"
services:
  cronjobshell:
    build:
      context: $ODOO_IMAGES/cronjobs
      args:
        WODOO_VERSION: $WODOO_VERSION
        POSTGRES_VERSION: $POSTGRES_VERSION
        APT_PROXY_IP: ${APT_PROXY_IP}
        PIP_PROXY_IP: ${PIP_PROXY_IP}
        APT_OPTIONS: ${APT_OPTIONS}
        DOCKER_GID: ${DOCKER_GID}
        # Dont do: if images used, then not compatible
        # OWNER_UID: $OWNER_UID
    profiles:
      - auto
    privileged: true
    restart: "unless-stopped"
    command: ['sleep']
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
    volumes:
      - "$ODOO_IMAGES/cronjobs/bin/:/usr/local/bin/:ro"
      - "${HOST_RUN_DIR}/cronjobs:/opt/cronjobs"
      - "$DUMPS_PATH:/host/dumps"
      - "${HOST_RUN_DIR}:/root/.odoo/run/$PROJECT_NAME"
      - "$ODOO_IMAGES:$ODOO_IMAGES"
      - ${HOST_CUSTOMS_DIR}:/opt/src
      - ${HOST_CUSTOMS_DIR}:${HOST_CUSTOMS_DIR}
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker