[metadata]
name = zodoo
version = 10.6.0
description_file = README.md
DESCRIPTION = Odoo Framework
URL = https://github.com/Odoo-Ninjas/zodoo
EMAIL = marc@itewimmer.de
AUTHOR = Marc-Christian Wimmer
license=MIT

[options]
python_requires = >=3.6.0

[options.entry_points]
console_scripts =
    odoo = zodoo:cli
