services:
  docker-proxy:
    image: tecnativa/docker-socket-proxy
    restart: "unless-stopped"
    profiles:
      - manual
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CONTAINERS: 1
      POST: 1
      VOLUMES: 0
      IMAGES: 0
      NETWORKS: 0
      EXEC: 1
      LOG_LEVEL: warning

  coding:
    labels:
      proxy_config: ${ODOO_IMAGES}/coding/proxy/coding.conf
    build:
      context: $ODOO_IMAGES/coding
    restart: "unless-stopped"
    profiles:
      - manual
    environment:
      OWNER_UID: ${OWNER_UID}
      DOCKER_HOST: tcp://docker-proxy:2375
    volumes:
      - ${HOST_CUSTOMS_DIR}:/opt/src
    depends_on:
      - docker-proxy
