# manage-order 1000
services:
  odoo_base:
    build:
        context: $ODOO_IMAGES/odoo
        dockerfile: $ODOO_IMAGES/odoo/config/${ODOO_VERSION}/Dockerfile
        args:
          ODOO_VERSION: ${ODOO_VERSION}
          ODOO_CONFIG_DIR: ${ODOO_CONFIG_DIR}
          ODOO_PYTHON_VERSION: ${ODOO_PYTHON_VERSION}
          INSTALL_DOCKER_CLIENTS: ${INSTALL_DOCKER_CLIENTS}
          DOCKER_GROUP_ID: ${DOCKER_GROUP_ID}
          ODOO_INSTALL_LIBPOSTAL: ${ODOO_INSTALL_LIBPOSTAL}
          PYPI_SERVER: ${PYPI_SERVER}
          APT_OPTIONS: ${APT_OPTIONS}
          APT_PROXY_IP: ${APT_PROXY_IP}
          DOCKER_GID: ${DOCKER_GID}
          USE_APT_MIRRORS: ${USE_APT_MIRRORS}
    restart: unless-stopped
    profiles:
      - auto
    volumes:
      - ${HOST_RUN_DIR}:/opt/run
      - ${HOST_RUN_DIR}/odoo_outdir:/opt/out_dir
      - ${HOST_RUN_DIR}/debug:/tmp/debug

      - ${ODOO_FILES}:/opt/files

