# manage-order 999
services:
  wodoo_src:
    build:
      context: $ODOO_IMAGES/wodoo
    profiles:
      - auto

  odoo_base:
    build:
        context: $ODOO_IMAGES/odoo
        dockerfile: $ODOO_IMAGES/odoo/config/${ODOO_VERSION_INT}/Dockerfile
        args:
          ODOO_VERSION: "${ODOO_VERSION_INT}"
          ODOO_CONFIG_DIR: ${ODOO_CONFIG_DIR}
          ODOO_PYTHON_VERSION: ${ODOO_PYTHON_VERSION}
    restart: unless-stopped
    environment:
      - IS_ODOO_CONTAINER=1
    profiles:
      - auto
    volumes:
      - ${HOST_RUN_DIR}:/opt/run
      - ${HOST_RUN_DIR}/odoo_outdir:/opt/out_dir
      - ${HOST_RUN_DIR}/debug:/tmp/debug
      - ${ODOO_FILES}:/opt/files

