services:
    vscode:
        build: 
          context: $ODOO_IMAGES/vscode
          args:
            OWNER_UID: $OWNER_UID
            DOCKER_GID: $DOCKER_GID
            APT_PROXY_IP: ${APT_PROXY_IP}
            APT_OPTIONS: ${APT_OPTIONS}
            PIP_PROXY_IP: ${PIP_PROXY_IP}
        cap_add:
          # required by vscode
          - SYS_ADMIN
        shm_size: 4gb
        restart: "unless-stopped"
        privileged: true
        profiles:
          - manual
        # ports:
        #     - "5900:5900"
        volumes:
          - ${HOST_CUSTOMS_DIR}:/opt/src
          - ${HOST_CUSTOMS_DIR}:${HOST_CUSTOMS_DIR}
          - ${ODOO_IMAGES}/vscode/user_data:/home/userdata
          - ${ODOO_IMAGES}/vscode/entrypoint.sh:/entrypoint.sh
          - ${ODOO_IMAGES}/vscode/start.sh:/start.sh
          - /var/run/docker.sock:/var/run/docker.sock
          - /var/lib/docker:/var/lib/docker
          - "${ODOO_IMAGES}:/home/user1/.odoo/images"
          - "${HOST_RUN_DIR}:/home/user1/.odoo/run/$PROJECT_NAME"
          - "${HOST_RUN_DIR}/gimera/cache:/home/user1/.cache/gimera"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - XPRA_RESIZE_DISPLAY=1
            - XPRA_HTML5_BASE=/code/
