#manage-order: 5000
services:
  proxy_abstract:
    build: $ODOO_IMAGES/proxy
    restart: unless-stopped
    profiles:
      - auto
    networks:
      - default
    volumes:
      - $HOST_RUN_DIR/proxy:/etc/proxy
      - $HOST_RUN_DIR/run/intercom:/intercom
      - $ODOO_IMAGES/proxy/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - $ODOO_IMAGES/proxy/static:/usr/local/openresty/nginx/static
      - $ODOO_IMAGES/proxy/lua:/usr/local/openresty/nginx/lua
      - $ODOO_IMAGES/proxy/conf.d:/usr/local/openresty/nginx/conf.d
      - ${CUSTOMS_DIR}:/usr/src/app/odoo
      - ${HOST_RUN_DIR}/odoo_outdir/robot_output:/robot_output
      - ${HOST_RUN_DIR}/proxy_logs:/root/.npm/_logs
      - ${ODOO_IMAGES}/proxy/lua/myngx.lua:/usr/local/openresty/luajit/share/lua/5.1/myngx.lua

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
