# proxy_host: coding:8081
location = /codevim {
    rewrite_by_lua_block {
        require("dashauth").gate(os.getenv("CODING_PASSWORD"), "/code", "zodoo code")
    }
    set $backend $default_target;
    access_by_lua_file "{lua_resolve_host}";
    rewrite ^ /vim/enable break;
    proxy_pass $backend;
}
location = /novim {
    rewrite_by_lua_block {
        require("dashauth").gate(os.getenv("CODING_PASSWORD"), "/code", "zodoo code")
    }
    set $backend $default_target;
    access_by_lua_file "{lua_resolve_host}";
    rewrite ^ /vim/disable break;
    proxy_pass $backend;
}
