# proxy_host: coding:8081
location = /codevim {
    set $backend $default_target;
    access_by_lua_file "{lua_resolve_host}";
    rewrite ^ /vim/enable break;
    proxy_pass $backend;
}
location = /novim {
    set $backend $default_target;
    access_by_lua_file "{lua_resolve_host}";
    rewrite ^ /vim/disable break;
    proxy_pass $backend;
}
