services:
  console:
    build:
      context: $ODOO_IMAGES/console
      args:
        WODOO_VERSION: $WODOO_VERSION
        OWNER_UID: $OWNER_UID
        DOCKER_GID: $DOCKER_GID
        project_name: $project_name
        # Dont do: if images used, then not compatible
        # OWNER_UID: $OWNER_UID
    privileged: true
    links:
        - webssh
        - proxy
    restart: "unless-stopped"
    profiles:
      - auto
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
    volumes:
      - "$ODOO_IMAGES/cronjobs/bin/:/usr/local/bin/:ro"
      - "${HOST_RUN_DIR}/cronjobs:/opt/cronjobs"
      - "$DUMPS_PATH:/host/dumps"
      - "${HOST_RUN_DIR}:/home/odoo/.odoo/run/$PROJECT_NAME"
      - "${ODOO_IMAGES}:$ODOO_IMAGES"
      - ${CUSTOMS_DIR}:/opt/src
      - ${CUSTOMS_DIR}:${CUSTOMS_DIR}
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker
      - ${ODOO_IMAGES}/console/entrypoint.sh:/entrypoint.sh
