services:
  webssh_console:
    build: 
      context: ${ODOO_IMAGES}/webssh
    restart: unless-stopped
    profiles:
      - auto
    labels:
      odoo_framework.apply_env: 0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${ODOO_IMAGES}/webssh/programs:/root/programs
    environment:
      - DOCKER_GID=${DOCKER_GID}