services:
  webssh_console:
    build: 
      context: ${ODOO_IMAGES}/webssh
      args: 
        APT_PROXY_IP: ${APT_PROXY_IP}
        USE_APT_MIRRORS: ${USE_APT_MIRRORS}
        PYPI_SERVER: ${PYPI_SERVER}
        APT_OPTIONS: ${APT_OPTIONS}
        DOCKER_GID: ${DOCKER_GID}
    restart: unless-stopped
    profiles:
      - auto
    labels:
      odoo_framework.apply_env: 0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${ODOO_IMAGES}/webssh/programs:/root/programs
  proxy:
    environment:
      WEBSSH_CONSOLE_HOST: http://webssh_console:8080
  console:
    build:
      context: $ODOO_IMAGES/console
      args:
        WODOO_VERSION: $WODOO_VERSION
        OWNER_UID: $OWNER_UID
        DOCKER_GID: $DOCKER_GID
        POSTGRES_VERSION: $POSTGRES_VERSION
        project_name: $project_name
        APT_PROXY_IP: ${APT_PROXY_IP}
        PYPI_SERVER: ${PYPI_SERVER}
        APT_OPTIONS: ${APT_OPTIONS}
        USE_APT_MIRRORS: ${USE_APT_MIRRORS}
        # Dont do: if images used, then not compatible
        # OWNER_UID: $OWNER_UID
    privileged: true
    links:
        - webssh_console
        - proxy
    restart: "unless-stopped"
    profiles:
      - auto
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
    volumes:
      - "$ODOO_IMAGES/cronjobs/bin/:/usr/local/bin/:ro"
      - "${HOST_RUN_DIR}/cronjobs:/opt/cronjobs"
      - "$DUMPS_PATH:/host/dumps"
      - "${HOST_RUN_DIR}:/home/odoo/.odoo/run/$PROJECT_NAME"
      - "${ODOO_IMAGES}:$ODOO_IMAGES"
      - ${HOST_CUSTOMS_DIR}:/opt/src
      - ${HOST_CUSTOMS_DIR}:${HOST_CUSTOMS_DIR}
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker
      - ${ODOO_IMAGES}/console/entrypoint.sh:/entrypoint.sh
