# manage-order: 5000
version: '3.3'
volumes:
  mailstorage:
  mailsqlite:

services:
  mail:
    build: 
      context: $ODOO_IMAGES/mail
      args:
        BUILD_HOST_IP: ${BUILD_HOST_IP}

    profiles:
      - auto
    volumes:
      - mailstorage:/home/postmaster/Maildir
      - mailsqlite:/rc
      - $ODOO_IMAGES/mail/bin:/opt/bin

  roundcube:
    build: 
      context: $ODOO_IMAGES/roundcube
      args:
        BUILD_HOST_IP: ${BUILD_HOST_IP}
    # ports:
    #    - "8282:80"
    profiles:
      - auto
    environment:
      MAIL_SERVER: ${project_name}_mail
