# manage-order: 5000
version: '3.3'
volumes:
  mailstorage:
  mailsqlite:

services:
  mail:
    build: $ODOO_IMAGES/mail
    profiles:
      - auto
    volumes:
      - mailstorage:/home/postmaster/Maildir
      - mailsqlite:/rc
      - $ODOO_IMAGES/mail/bin:/opt/bin

  roundcube:
    build: $ODOO_IMAGES/roundcube
    # ports:
    #    - "8282:80"
    profiles:
      - auto
    environment:
      MAIL_SERVER: ${project_name}_mail
