FROM postgres:17-bullseye
CMD ["postgres"]

#___SNIPPET_APT_PROXY___
RUN #___SNIPPET_APT_INSTALL___ \
postgresql-server-dev-17 python-dev build-essential git python3-pip procps sockstat && \
#___SNIPPET_APT_INSTALL___ \
postgresql-17-postgis-3 ncdu


COPY config* /
COPY run.sh /run.sh
COPY init/* /docker-entrypoint-initdb.d/
RUN chown -R postgres:postgres /docker-entrypoint-initdb.d && \
    chmod a+x /docker-entrypoint-initdb.d/*.sh /run.sh

#___SNIPPET_CLEANUP___
RUN rm -Rf \
/usr/share/perl \
/usr/lib/gcc \
/usr/lib/llvm-* \
/usr/lib/aarch*/perl \
/usr/lib/python2.7 \
/var/lib/apt/lists/* \
/usr/lib/dpkg \
/usr/lib/bfd-plugins \
/usr/lib/git-core

RUN apt-get purge -y git git-core gnupg gnupg2 binutils
RUN apt-get purge -y libgdal* libarmadillo* libogdi* libasan* libtsan* libubsan*

#/usr/lib/python*
#/usr/lib/aarch* \