FROM postgres:16-bullseye
ARG APT_PROXY_IP
ARG APT_OPTIONS
CMD ["postgres"]

#___SNIPPET_APT_PROXY___
RUN apt update && apt $APT_OPTIONS install -y \
postgresql-server-dev-16 python-dev build-essential git python3-pip procps sockstat && \
apt $APT_OPTIONS install -y postgresql-16-postgis-3


COPY config* /
COPY run.sh /run.sh
COPY init/* /docker-entrypoint-initdb.d/
RUN chown -R postgres:postgres /docker-entrypoint-initdb.d && \
    chmod a+x /docker-entrypoint-initdb.d/*.sh /run.sh
