FROM postgres:11-bullseye
ARG APT_PROXY_IP
ARG APT_OPTIONS
CMD ["postgres"]
RUN echo "Acquire::http::Proxy \"http://${APT_PROXY_IP}:3142\";" > /etc/apt/apt.conf.d/01proxy
RUN apt-get update && \
apt $APT_OPTIONS install -y postgresql-server-dev-12 python-dev build-essential git python3-pip procps sockstat


ADD config* /
ADD run.sh /run.sh
COPY init/* /docker-entrypoint-initdb.d/
RUN chown -R postgres:postgres /docker-entrypoint-initdb.d && \
    chmod a+x /docker-entrypoint-initdb.d/*.sh /run.sh
