FROM postgres:12-bullseye
ARG APT_PROXY_IP
ARG APT_OPTIONS
CMD ["postgres"]


#___SNIPPET_APT_PROXY___
RUN #___SNIPPET_APT_INSTALL___ \
postgresql-server-dev-12 python-dev build-essential git python3-pip procps sockstat

COPY config* /
COPY run.sh /run.sh
COPY init/* /docker-entrypoint-initdb.d/
RUN chown -R postgres:postgres /docker-entrypoint-initdb.d && \
    chmod a+x /docker-entrypoint-initdb.d/*.sh /run.sh
