ARG BUILD_HOST_IP
FROM postgres:16-bullseye
CMD ["postgres"]
RUN echo "Acquire::http::Proxy \"http://${BUILD_HOST_IP}:3142\";" > /etc/apt/apt.conf.d/01proxy
RUN apt update && \
apt install -y postgresql-server-dev-16 python-dev build-essential git python3-pip procps sockstat
RUN apt install -y postgresql-16-postgis-3


ADD config* /
ADD run.sh /run.sh
COPY init/* /docker-entrypoint-initdb.d/
RUN chown -R postgres:postgres /docker-entrypoint-initdb.d && \
    chmod a+x /docker-entrypoint-initdb.d/*.sh /run.sh
