FROM postgres:13-bullseye
CMD ["postgres"]

#___SNIPPET_APT_PROXY___
RUN #___SNIPPET_APT_INSTALL___ \
postgresql-server-dev-13 python-dev build-essential git python3-pip procps sockstat


COPY config* /
COPY run.sh /run.sh
COPY init/* /docker-entrypoint-initdb.d/
RUN chown -R postgres:postgres /docker-entrypoint-initdb.d && \
    chmod a+x /docker-entrypoint-initdb.d/*.sh /run.sh
