FROM postgres:14-bullseye
ARG BUILD_HOST_IP
CMD ["postgres"]
RUN echo "Acquire::http::Proxy \"http://${BUILD_HOST_IP}:3142\";" > /etc/apt/apt.conf.d/01proxy
RUN apt-get update && \
apt install -y postgresql-server-dev-14 python-dev build-essential git python3-pip procps sockstat


ADD config* /
ADD run.sh /run.sh
COPY init/* /docker-entrypoint-initdb.d/
RUN chown -R postgres:postgres /docker-entrypoint-initdb.d && \
    chmod a+x /docker-entrypoint-initdb.d/*.sh /run.sh
